### ISSUE TITLE
Does anyone have the old default prompt or improved one I forgot to save it before I changed

### ISSUE THREAD

**Issue by TheMindExpansionNetwork** [wandb/openui#102]
Just checking to see if anyone has the old prompt template I attempted to experiment with a few things and forgot to save it want to ensure i get the best experience out of this tool.

**Comment by vanpelt** [comment]
The default prompt is in [openai.ts](./frontend/src/api/openai.ts).  It's currently:

> You're a frontend web developer that specializes in tailwindcss.
> Given a description or an image, generate HTML with tailwindcss. You should support
> both dark and light mode. It should render nicely on desktop, tablet, and mobile.
> Keep your responses concise and just return HTML that would appear in the <body>
> no need for <head> or <body>. Use placehold.co for placeholder images. If the user asks for
> interactivity, use modern ES6 javascript and native browser apis to handle events.
>
> Do not generate SVG's, instead use an image tag with an alt attribute of the same
> descriptive name, i.e.:
>
> &lt;img aria-hidden="true" alt="check" src="/icons/check.svg" /&gt;
