### ISSUE TITLE
Error executing OpenUI

### ISSUE THREAD

**Issue by kakachiex2** [wandb/openui#110]
I'm getting this error on windows 

(OpenUI) PS C:\OpenUI\openui\backend> python -m openui
Traceback (most recent call last):
  File "C:\Users\rafae\miniconda3\envs\OpenUI\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\rafae\miniconda3\envs\OpenUI\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\OpenUI\openui\backend\openui\__main__.py", line 3, in <module>
    from . import server
  File "C:\OpenUI\openui\backend\openui\server.py", line 35, in <module>
    from .util import storage
  File "C:\OpenUI\openui\backend\openui\util\__init__.py", line 1, in <module>
    from .screenshots import gen_screenshots
  File "C:\OpenUI\openui\backend\openui\util\screenshots.py", line 3, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
(OpenUI) PS C:\OpenUI\openui\backend>

**Comment by playhousehosting** [comment]
I'm also getting something similar on ubuntu

**Comment by RyuSeiri** [comment]
(docker) i'm get same error on macos:

image:
![スクリーンショット 2024-05-13 12 55 51](https://github.com/wandb/openui/assets/56245152/908004b3-7ec7-490d-8e34-a32eb5feffe6)

**Comment by riazbapoo** [comment]
same issue here

**Comment by jawasch** [comment]
I traced the Issue back to not installed playwright and pillow packages. 
In the [file openui/backend/openui/pyproject.toml](https://github.com/wandb/openui/blob/main/backend/pyproject.toml) these two packages are mentioned inside 
`[project.optional-dependencies]
test = ["pytest", "pre-commit"]
eval = [
    "Pillow>=8.3.1",
    "playwright>=1.41.0",
    "beautifulsoup4>=4.0.0",
    "mistletoe>=1.0.0",
]`
After i have replaced them at 
`[project]
dependencies = [
    "weave@git+https://github.com/wandb/weave.git@fix/tiktoken-images",
    "openai>=1.12.0",
    "ollama>=0.1.7",
    "itsdangerous>=2.0.1",
    "peewee>=3.0.0",
    "fastapi>=0.108.0",
    "uvicorn>=0.25.0",
    "fastapi-sso>=0.13.0",
    "boto3>=1.34.67",
    "Pillow>=8.3.1",
    "playwright>=1.41.0",
]`
for me the Container is starting and running.

**Comment by wmsmigiel** [comment]
> I traced the Issue back to not installed playwright and pillow packages. In the [file openui/backend/openui/pyproject.toml](https://github.com/wandb/openui/blob/main/backend/pyproject.toml) these two packages are mentioned inside `[project.optional-dependencies] test = ["pytest", "pre-commit"] eval = [ "Pillow>=8.3.1", "playwright>=1.41.0", "beautifulsoup4>=4.0.0", "mistletoe>=1.0.0", ]` After i have replaced them at `[project] dependencies = [ "weave@git+https://github.com/wandb/weave.git@fix/tiktoken-images", "openai>=1.12.0", "ollama>=0.1.7", "itsdangerous>=2.0.1", "peewee>=3.0.0", "fastapi>=0.108.0", "uvicorn>=0.25.0", "fastapi-sso>=0.13.0", "boto3>=1.34.67", "Pillow>=8.3.1", "playwright>=1.41.0", ]` for me the Container is starting and running.

I had the same issue, adding pillow and playwright fixed it for me, Thanks!

**Comment by kakachiex2** [comment]
after install playwright and pillow I'm getting this error:
Loading personal and system profiles took 679ms.
(base) PS C:\OpenUI\openui\backend> python -m openui
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\OpenUI\openui\backend\openui\__main__.py", line 3, in <module>
    from . import server
  File "C:\OpenUI\openui\backend\openui\server.py", line 68, in <module>
    openai = AsyncOpenAI(
             ^^^^^^^^^^^^
  File "C:\Users\rafae\miniconda3\Lib\site-packages\openai\_client.py", line 316, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
(base) PS C:\OpenUI\openui\backend>

**Comment by kakachiex2** [comment]
Ok fixed by setting OpenAI environment variable

**Comment by SFARPak** [comment]
This error 
ModuleNotFoundError: No module named 'PIL'

is resolved by installing Pillow package

`python -m pip install Pillow`

**Comment by Swallow74** [comment]
> This error ModuleNotFoundError: No module named 'PIL'
> 
> is resolved by installing Pillow package
> 
> `python -m pip install Pillow`

To me this solution did not solve the problem, neither on Windows nor on Mac. The previous version of OpenUI worked regularly for me, though.

**Comment by hanpham32** [comment]
@Swallow74 could you please provide the error message you received?

**Comment by Swallow74** [comment]
> @Swallow74 could you please provide the error message you received?

I am really dumb, sorry... I was running OpenUI with Pinokio, and I didn't realize that this launcher uses its own conda environment, and so I had to install Pillow inside this env. Sorry again for reporting a problem related to external code.

**Comment by niktekusho** [comment]
This is the traceback of commands I run to make openui work for me on macOs (using a local codellama instance):

```sh
cd backend
python -m pip install Pillow playwright
OPENAI_API_KEY='' python -m openui
```

**Comment by vanpelt** [comment]
crap, sorry everyone.  I just fixed this in the `main` branch, Pillow and playwright are no longer pulled in by default.  We only use them if you're doing evaluations of different prompts / models, more to come there.  

If anyone get's this now another quick fix would be to run the following from within the `backend` directory:

```bash
pip install .[eval]
```

**Comment by liuqiyu** [comment]
> Ok fixed by setting OpenAI environment variable

How to set up in Windows

**Comment by liuqiyu** [comment]
> Ok fixed by setting OpenAI environment variable


How to set up in Win10 @kakachiex2
