### ISSUE TITLE
How can i add an option to the "convert to"

### ISSUE THREAD

**Issue by frappierer** [wandb/openui#111]
Currently it looks like:
![image](https://github.com/wandb/openui/assets/4376185/05892ca0-b965-4465-9416-d57b1b7b0cd3)

Lets say i want to add Vanilla JS. How can i do that?
Best

**Comment by frappierer** [comment]
Found it.
Only thing i have to do is to edit the history.ts correct?

**Comment by vanpelt** [comment]
Yep, that should do it.  However I'm not sure vanilla JS would really make sense here.  The model generates HTML and vanilla JS by default so there shouldn't need to be any conversion.  The values in `history.ts` ultimately get sent to a an LLM with the prompt: `Please turn this into a ${framework} component.` and then it provides the existing HTML and javascript generated so I can't really imagine any conversion happening in the Vanilla JS case.
