### ISSUE TITLE
is possible to run with Docker / Docker Compose?

### ISSUE THREAD

**Issue by grigio** [wandb/openui#13]
I've seen a Dockerfile but it seems just for the backend

**Comment by vanpelt** [comment]
Hey @grigio [that container](https://github.com/wandb/openui/blob/main/backend/Dockerfile) runs the service!  I'll add something to the README, but for now:

```
cd backend
docker build . -t wandb/openui --load
docker run -p 7878:7878 -e OPENAI_API_KEY wandb/openui
```

Additionally I add a [dev container configuration](https://github.com/wandb/openui/blob/main/.devcontainer/devcontainer.json) to the repo for running a dev env locally or in GH Codespaces!

**Comment by grigio** [comment]
Thanks, can you specify how to set the ollama url for the `docker run` ? it seems hardcoded
https://github.com/wandb/openui/blob/8fef850f42c58cb36d32909851cb736d9adb4c1d/frontend/src/api/ollama.ts#L6
