### ISSUE TITLE
Exporting complete HTML and CSS

### ISSUE THREAD

**Issue by cashgarman** [wandb/openui#130]
Excellent project first of all!

Unless I am missing something, copying or saving the resulting HTML into something usable, it only seems to copy small portion of the HTML, with a lot of the CSS styling missing.

**Comment by cashgarman** [comment]
Page in OpenUI:
![image](https://github.com/wandb/openui/assets/3536610/9ea0c7a5-cb63-4e08-986a-c335fda4678d)

Page in browser after copying the HTML into a .html file:
![image](https://github.com/wandb/openui/assets/3536610/318db1c9-cf73-4315-898c-09c314c292f3)

**Comment by VideoFX** [comment]
I just ran into this as well. Is there a reference to the rest of the files needed to complete this?

**Comment by vanpelt** [comment]
@VideoFX @cashgarman I just pushed a change to main and deployed to the demo app.  Copying or downloading now includes the needed wrapper to render properly.  For future reference the needed template is:

```html
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body>
    ${code}
  </body>
</html>
```
