### ISSUE TITLE
Page in OpenUI:B5690EEEBB952194

### ISSUE THREAD

**Issue by Pennuaju** [wandb/openui#133]
Page in OpenUI:
![image](https://github.com/wandb/openui/assets/3536610/9ea0c7a5-cb63-4e08-986a-c335fda4678d)

Page in browser after copying the HTML into a .html file:
![image](https://github.com/wandb/openui/assets/3536610/318db1c9-cf73-4315-898c-09c314c292f3)

_Originally posted by @cashgarman in https://github.com/wandb/openui/issues/130#issuecomment-2116210730_

**Comment by vanpelt** [comment]
Wow, that's a sick login page!  I'm getting this fixed now, until then you can wrap you're html with the following to include tailwind:

```html
<html>
	<head>
	<meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
	</head>
	<body>
${code}
	</body>
</html>
```
