### ISSUE TITLE
Could you add the feature of hosting in the local network?

### ISSUE THREAD

**Issue by charleshuangruo** [wandb/openui#136]
How could I change some code to host the application for other devices in the local network and enable them to access to “http://[local_ip hosting the app]: [port]” without using Docker? Or will it be supported in the future? Thanks!

**Comment by vanpelt** [comment]
You can just set the `OPENUI_ENVIRONMENT=production` environment variable and the server will listen on 0.0.0.0 instead of 127.0.0.1.  This would allow you to talk to it from other machines in the network.

**Comment by imlida** [comment]
I hope to use it directly locally without logging in and enable 0.0.0.0 access at the same time. I hope such settings can be added.

**Comment by FlomoN** [comment]
Would be amazing if `OPENUI_ENVIRONMENT=production` was documented in the readme. Took me a while to find this setting here in the issues :)
