### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by robin-collins** [wandb/openui#146]
Couple of things that would be very helpful.

 - The ability to edit the code in the box below and be able to save it. This would allow for the user to make tweaks changes, before asking the AI to make modifications.
 - The ability to get it to roll back a change (I can see the chat history, and can copy code from there, but there is no way to then use that code back in the AI editor environment)
 
I also like the suggestion about using diff's suggested by someone in regards to how the project ['aider'](https://github.com/paul-gauthier/aider) does it.

Great idea, I can see it will be fantastic when matured.

**Comment by vanpelt** [comment]
Hey @robin-collins, thanks for the suggestions.  I'm happy to report that I'm working on both of your bullet points currently!

I haven't started looking into diff's but love the idea as well.  I'll keep this issue open and let you know when I push the changes.

**Comment by sunnysonx** [comment]
@vanpelt great news! Subscribing to it! 🔔🚀

**Comment by vanpelt** [comment]
This is now in the latest release!
