### ISSUE TITLE
Feature request: Undo/Amend last API response

### ISSUE THREAD

**Issue by sunnysonx** [wandb/openui#149]
Hello, 

Currently if the API fails to fulfil your request, it will basically erase the existing HTML, for example:
![image](https://github.com/wandb/openui/assets/14160283/371ef8f3-5f44-4b0e-af9d-b63284f7dba9)

If we check the chat history, I have the following response:
![image](https://github.com/wandb/openui/assets/14160283/d279fef7-1495-4a8f-9858-fc555ba2c94a)

So basically everything I did prior it, was just erased. It happens quite often that the API will not return what exactly I need and it destroys everything you created previously.

Thank you

**Comment by vanpelt** [comment]
This now exists in the latest release via the new history sidebar.  Just hover over a version and you can click the trash icon.
