### ISSUE TITLE
Never ending loop (duh) 

### ISSUE THREAD

**Issue by cardonasMind** [wandb/openui#15]
I asked to make 5 more cards and make them horizontally scrollable and doesn't get it, am I not asking properly? 

https://openui.fly.dev/ai/gw7asmYSEDtsNG4YhjwcA

**Comment by vanpelt** [comment]
The model can be finicky.  I suggest trying to ask for it in a few different ways.  You can also try tweaking the system prompt or altering the temperature by clicking the settings gear in the upper left.
