### ISSUE TITLE
This is mind blowing 

### ISSUE THREAD

**Issue by Pixel-Panda** [wandb/openui#151]
Sorry to fill up issues but you deserve such praise for this project. Absolutely phenomenal work.

**Comment by sontoriyama** [comment]
¡Error inesperado de aplicación!
No se pudo ejecutar 'removeChild' en 'Nodo': el nodo que se va a eliminar no es hijo de este nodo.
Error: No se pudo ejecutar 'removeChild' en 'Nodo': el nodo que se va a eliminar no es hijo de este nodo.
    en Ym (http://127.0.0.1:7878/assets/vendor-QOAI5TVB.js:40:26061)
    en Sn (http://127.0.0.1:7878/assets/vendor-QOAI5TVB.js:40:25767)
    en Ym (http://127.0.0.1:7878/assets/vendor-QOAI5TVB.js:40:26298)
    en Sn (http://127.0.0.1:7878/assets/vendor-QOAI5TVB.js:40:25767)
    en Ym (http://127.0.0.1:7878/assets/vendor-QOAI5TVB.js:40:26516)
    en Sn (http://127.0.0.1:7878/assets/vendor-QOAI5TVB.js:40:25767)
    en Ym (http://127.0.0.1:7878/assets/vendor-QOAI5TVB.js:40:25961)
    en Sn (http://127.0.0.1:7878/assets/vendor-QOAI5TVB.js:40:25767)
    en Ym (http://127.0.0.1:7878/assets/vendor-QOAI5TVB.js:40:26516)
    en Sn (http://127.0.0.1:7878/assets/vendor-QOAI5TVB.js:40:25767)
