### ISSUE TITLE
Unable to clone: fatal: early EOF

### ISSUE THREAD

**Issue by Pixel-Panda** [wandb/openui#159]
Cloning into 'openui'...
remote: Enumerating objects: 1053, done. fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

**Comment by Pixel-Panda** [comment]
Would be nice to get a CodeSandbox of this. Its been impossible trying to get this repo working.
<img width="1590" alt="image" src="https://github.com/wandb/weave/assets/63879450/c990d54e-7054-4634-99d2-7b710a4f04f4">

**Comment by vanpelt** [comment]
The readme has instructions for a GitHub code space or Gitpod.  The error you're getting is a network error on GitHub's side and should go away if you retry.

**Comment by Pixel-Panda** [comment]
> The readme has instructions for a GitHub code space or Gitpod.  The error you're getting is a network error on GitHub's side and should go away if you retry.

Apologies I wish delete this issue as it was totally user side.
