### ISSUE TITLE
styling is an issue

### ISSUE THREAD

**Issue by Pixel-Panda** [wandb/openui#160]
feature note: add ability in code to actually use shadcn or tamagui or something. So far...this is...nasty. Love the tech but its unusable atm. Everything is just buttons and squares. I can add this to the code but would like to see the team's approach first.

**Comment by vanpelt** [comment]
This is coming!  Hopefully by tomorrow.  I haven't wired up a UI to modify the color scheme, but I've setup tailwind to use utility classes like primary, muted, etc.  you'll be able to customize them in the generated HTML.  Would love to have someone run with extending the ability to customize once I release.

**Comment by vanpelt** [comment]
This is now merged!  You can now choose from a variety of color schemes.
