### ISSUE TITLE
horrible documentation

### ISSUE THREAD

**Issue by josersleal** [wandb/openui#164]
specially the readme file. purely horrible. devs making docs for robots

**Comment by samuelrey** [comment]
This isn't actionable feedback. Maybe you could recommend rearranging a specific section or rewording a sentence.

**Comment by vanpelt** [comment]
Thanks @samuelrey.  @josersleal are you trolling?  I've spent a good amount of time working on the README.  I've got a [bunch of changes](https://github.com/wandb/openui/pull/163/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) coming hopefully later today.  I'm always happy to continue iterating and improving but feedback like this only upsets me.  I'll close this ticket for now and reopen if you actually provide useful feedback.
