### ISSUE TITLE
Prompt input field is white on white. Android , Brave Browser

### ISSUE THREAD

**Issue by nessystudio** [wandb/openui#168]
After the latest update your live preview site looks great, but the input text is white on white.

**Comment by vanpelt** [comment]
Thanks nessy! Can you share a screenshot so I'm sure I can reproduce what you're seeing?

**Comment by EyeSeeThru** [comment]
Same as shown in screenshot on Arc Browser Mac desktop, with all updated to latest versions.

**Comment by vanpelt** [comment]
Thanks, I wasn't using darkmode by default.  Just fixed and pushed the fix to main!

<img width="963" alt="Screenshot 2024-06-26 at 2 35 14 PM" src="https://github.com/wandb/openui/assets/17/be7b5592-843f-4b5b-9f1d-715a8b6becbc">
