### ISSUE TITLE
ModuleNotFoundError: No module named 'weave.monitoring'

### ISSUE THREAD

**Issue by baoyongren** [wandb/openui#179]
ModuleNotFoundError: No module named 'weave.monitoring'
![error](https://github.com/wandb/openui/assets/175103913/cceac549-ec0b-40d4-913d-cef841003b56)

**Comment by vanpelt** [comment]
Sorry about that, I just pushed a fix to the main branch.  It should work now.l

**Comment by baoyongren** [comment]
thanks,well done
