### ISSUE TITLE
Looking for suggestion for a better generation

### ISSUE THREAD

**Issue by zoultrex** [wandb/openui#184]
I have just run openUI from docker and I'm using Gemini 1.5 pro, should I try another model?
Some very simple things were not present at all for example background color, correct spacing between elements, missing simple sections altogether (a paragraph with 4 words and also a menu with 4 links in between sections)

**Comment by vanpelt** [comment]
One approach is to just tell the model to fix the errors you're seeing.  The best model I've tried so far is Claude 3.5 Sonnet, the OpenAI models are really good too.  I personally haven't experimented much with the Gemeni models.
