### ISSUE TITLE
All things I have created are broken when I open them in the browser!

### ISSUE THREAD

**Issue by alfi4000** [wandb/openui#19]
All things I have created are broken when I open them in the browser!
What is the issue?

<body class="font-sans antialiased text-zinc-900 dark:text-zinc-100 dark:bg-zinc-800">
  <nav class="bg-white dark:bg-zinc-900 shadow-md">
    <div class="max-w-6xl mx-auto px-4">
      <div class="flex justify-between">
        <div class="flex space-x-4">
          <div>
            <a href="#" class="flex items-center py-5 px-2 text-zinc-700 hover:text-zinc-900 dark:hover:text-white">
              <span class="font-bold">Artist's Name</span>
            </a>
          </div>
          <div class="hidden md:flex items-center space-x-1">
            <a href="#" class="py-5 px-3 text-zinc-700 hover:text-zinc-900 dark:hover:text-white">Home</a>
            <a href="#" class="py-5 px-3 text-zinc-700 hover:text-zinc-900 dark:hover:text-white">Gallery</a>
            <a href="#" class="py-5 px-3 text-zinc-700 hover:text-zinc-900 dark:hover:text-white">About</a>
            <a href="#" class="py-5 px-3 text-zinc-700 hover:text-zinc-900 dark:hover:text-white">Contact</a>
          </div>
        </div>
      </div>
    </div>
  </nav>

  <header class="max-w-6xl mx-auto mt-12 text-center">
    <h1 class="text-4xl font-bold">Welcome to My Artwork</h1>
    <p class="text-zinc-600 dark:text-zinc-400 mt-2">A collection of my recent works</p>
  </header>

  <main class="max-w-6xl mx-auto mt-8 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 px-4">
    <div class="overflow-hidden rounded-lg shadow-lg">
      <img src="https://placehold.co/600x400" alt="Artwork 1" class="w-full h-auto">
    </div>
    <div class="overflow-hidden rounded-lg shadow-lg">
      <img src="https://placehold.co/600x400" alt="Artwork 2" class="w-full h-auto">
    </div>
    <div class="overflow-hidden rounded-lg shadow-lg">
      <img src="https://placehold.co/600x400" alt="Artwork 3" class="w-full h-auto">
    </div>
    
  </main>

  <footer class="bg-white dark:bg-zinc-900 text-center py-4 mt-12">
    <p>© 2023 Artist's Name. All rights reserved.</p>
  </footer>

  <script>
    document.querySelectorAll('nav a').forEach(link => {
      link.addEventListener('click', function(e) {
        e.preventDefault();
        alert('This would lead to a different section.');
      });
    });
  </script>
</body>

**Comment by vanpelt** [comment]
@alfi4000 the html that you copy assumes the webpage it get's rendered in has tailwindcss setup.  You can wrap the HTML in the following for it to render properly:

```html
<!doctype html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
  <!-- The Generated HTML should go here --->
</body>
</html>
```

For production setups you'll likely want to use something like [Vite](https://vitejs.dev) to pre-compile the tailwind styles.

**Comment by alfi4000** [comment]
Ok Thanks for the help!

**Comment by alfi4000** [comment]
> @alfi4000 the html that you copy assumes the webpage it get's rendered in has tailwindcss setup. You can wrap the HTML in the following for it to render properly:
> 
> ```
> <!doctype html>
> <html>
> <head>
>   <meta charset="UTF-8">
>   <meta name="viewport" content="width=device-width, initial-scale=1.0">
>   <script src="https://cdn.tailwindcss.com"></script>
> </head>
> <body>
>   
> </body>
> </html>
> ```
> 
> For production setups you'll likely want to use something like [Vite](https://vitejs.dev) to pre-compile the tailwind styles.

But would it still work with tailwindcss on a website because I wanted to use it as front end for my wordpress website I am not a dev I just wanted to use it in a custom html block!

**Comment by alfi4000** [comment]
Oh it is some kind of programming language so when it is installed do I still need the script src call?  I found a plug that enables the tailwindcss usage on a website! : https://wordpress.org/plugins/website-builder/#description

**Comment by vanpelt** [comment]
Nice, yeah that should work!

**Comment by alfi4000** [comment]
> Nice, yeah that should work!

Ok
