### ISSUE TITLE
how to change the model when I switch to other LLM service?

### ISSUE THREAD

**Issue by hunter2009pf** [wandb/openui#203]
I have set up OPENAI_API_KEY and OPENAI_BASE_URL to other LLM but met error shown as below.
![image](https://github.com/user-attachments/assets/6faa8f92-19b5-418f-ae91-15714ea913f5)

**Comment by vanpelt** [comment]
I've added two new environment variables to allow for arbitrary openai compatible resources as [described here in the readme](https://github.com/wandb/openui?tab=readme-ov-file#running-locally).

```
OPENAI_COMPATIBLE_URL=https://whatever.com/v1
OPENAI_COMPATIBLE_API_KEY=xxx
```
