### ISSUE TITLE
styling to use certain library like tailwind?

### ISSUE THREAD

**Issue by afeezaziz** [wandb/openui#21]
wondering whether the code written can be constrained to a certain library eg. bootstrap or bulma or tailwind so that it can be consistent and easier to handle mobile responsive.

**Comment by vanpelt** [comment]
@afeezaziz my system prompt and rendering setup is made to only support tailwind.  It would be fairly easy to create a system to convert between the different frameworks with the LLM but rendering would be a little trickier.  The logic for converting between frameworks is here: 

1. [Frontend](https://github.com/wandb/openui/blob/main/frontend/src/components/CodeViewer.tsx#L72)
2. [API / LLM](https://github.com/wandb/openui/blob/main/frontend/src/api/openai.ts#L116-L119)
3. [IFrame Tailwind Renderer](https://github.com/wandb/openui/blob/main/frontend/public/annotator/index.html)
