### ISSUE TITLE
On my own machine and see "Login To enforce usage quotas an account is required."

### ISSUE THREAD

**Issue by villajo** [wandb/openui#22]
I don't know why this is. I'm using my own system to host with my own api key. Why would there need to be usage quotas on something that's open source and using my own personal systems and API key for generation?

**Comment by vanpelt** [comment]
Sorry this was a bug that took me longer to fix than I had hoped.  Just pushed the fix to main.  If you run the following it should work now!

```
git pull origin main
cd backend
pip install -U .
python -m openui
```

Let me know if it's still an issue, I'll close for now.
