### ISSUE TITLE
I generated the component and then downloaded the code seems to be missing css causing the component to not work, is there something wrong with my configuration?

### ISSUE THREAD

**Issue by kiliyxiaohao** [wandb/openui#25]
![image](https://github.com/wandb/openui/assets/128876653/d4afe603-85b4-4528-9d8e-bddd0fc9687d)
As title  
![image](https://github.com/wandb/openui/assets/128876653/4e6101b0-9451-4b07-9342-e734da74a9f2)
The output code is displayed as above

**Comment by kiliyxiaohao** [comment]
![image](https://github.com/wandb/openui/assets/128876653/db103088-0f4f-449b-b1f0-68fe86417719)
what！！！1

**Comment by vanpelt** [comment]
The generated HTML uses tailwind, you need to render it in a page that has tailwind configured.  Here's an example layout for development environments.  I'm also linking to a [similar issue](https://github.com/wandb/openui/issues/19) which also mentions getting it to work in wordpress.

```html
<!doctype html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
  <!-- The Generated HTML should go here --->
</body>
</html>
```
