### ISSUE TITLE
docker image not working properly ?

### ISSUE THREAD

**Issue by efi20232** [wandb/openui#26]
i am running 
docker run -p 7878:7878 -e OPENAI_API_KEY=xxxxxxxxx wandb/openui

its working and says 

wandb: Unpatching OpenAI completions
INFO (openui):  Starting OpenUI AI Server created by W&B...
INFO (openui):  Running API Server
INFO (uvicorn.error):  Started server process [1]
INFO (uvicorn.error):  Waiting for application startup.
DEBUG (openui):  Starting up server in 1...
INFO (uvicorn.error):  Application startup complete.
INFO (uvicorn.error):  Uvicorn running on http://127.0.0.1:7878 (Press CTRL+C to quit)

i go to the the link it open chrome and says
This site can’t be reachedThe connection was reset.
Try:

Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_RESET

**Comment by vanpelt** [comment]
Sorry about this guys, I forgot to update the README, but it's [updated now](https://github.com/wandb/openui?tab=readme-ov-file#docker)!  You'll need to run:

```bash
docker run -p 7878:7878 -e OPENUI_ENVIRONMENT=prod -e OPENAI_API_KEY wandb/openui
```

And that should fix it!
