### ISSUE TITLE
Support for UI libraries like Primevue

### ISSUE THREAD

**Issue by ZiadJ** [wandb/openui#29]
Is there any chance that we can specify a 3rd party component library as the building blocks any time soon?

**Comment by vanpelt** [comment]
Hey ZiadJ, we currently do support converting the raw tailwind HTML into a component framework.  The circle + button by the HTML panel allows you to choose frameworks like Svelte, React, etc.  You could add "Primevue" to [this list](https://github.com/wandb/openui/blob/main/frontend/src/state/atoms/history.ts#L13) *(be sure to add it to the type above as well)* in your local checkout and it might just work!

<img width="226" alt="convert framework" src="https://github.com/wandb/openui/assets/17/2aa2b1e7-c81b-4edf-9966-9467746b3c46">

If you were thinking of something else, would love to hear more about what you're imagining.
