### ISSUE TITLE
Deployment on Fly.io

### ISSUE THREAD

**Issue by scooter7** [wandb/openui#31]
Hi,

How did you deploy this to fly.io?

Would you please provide instructions?

Thanks!

**Comment by vanpelt** [comment]
Hey @scooter7 you bet.  Here are the steps:

First you'll want to change the OPENUI_HOST and GITHUB_CLIENT_ID environment variables in `backend/fly.toml`.  You can create a GitHub Oauth app in your developer settings.

```bash
cd backend
fly secrets set GITHUB_CLIENT_SECRET=xxx
fly secrets set OPENAI_API_KEY=xxx
fly volumes create openui_data --size 10
fly deploy
```

I haven't tried this from scratch so I might be missing something, but that *should do it...

**Comment by scooter7** [comment]
Thanks, @vanpelt , I'll try it and let you know how it goes. Thanks again!
