### ISSUE TITLE
Ollama gen error: unconverted data remains: Z

### ISSUE THREAD

**Issue by MMoneer** [wandb/openui#34]
Hi, response with 2 or 3 code lines then the error
DEBUG (openui):  Encoding llama data
DEBUG (openui):  Booting up ollama...
INFO (uvicorn.access):  127.0.0.1:52308 - "POST /v1/chat/completions HTTP/1.1" 200
ERROR (openui):  Ollama gen error: unconverted data remains: Z
DEBUG (openui):  Encoding llama data
DEBUG (openui):  Booting up ollama...
INFO (uvicorn.access):  127.0.0.1:52520 - "POST /v1/chat/completions HTTP/1.1" 200
ERROR (openui):  Ollama gen error: unconverted data remains: Z
<img width="1921" alt="brave_03042024_055" src="https://github.com/wandb/openui/assets/18519387/23975449-0edd-4bbc-b5b0-6f65e61f1dec">

**Comment by vanpelt** [comment]
@MMoneer I just [pushed a fix ](https://github.com/wandb/openui/commit/9aeff3503fe46c907ca8a6db6dfa0e4819cfe903) that should resolve this, not sure what's going on exactly but can you try pulling and seeing if you still get the error?

**Comment by itsmebcc** [comment]
That seems to have fixed it.

**Comment by MMoneer** [comment]
> @MMoneer I just [pushed a fix ](https://github.com/wandb/openui/commit/9aeff3503fe46c907ca8a6db6dfa0e4819cfe903) that should resolve this, not sure what's going on exactly but can you try pulling and seeing if you still get the error?

Thank you, for fixing the issue, this is the fastest issue solved with code fixing. 💯 🥇
