### ISSUE TITLE
I created a docker compose file for easily deployment on docker but I am a beginner in docker have you and idea what I have to edit

### ISSUE THREAD

**Issue by alfi4000** [wandb/openui#35]
I created a docker compose file for easily deployment on docker but I am a beginner in docker have you and idea what I have to edit to get rid of the error here?: 
<img width="1327" alt="Bildschirmfoto 2024-04-03 um 17 50 56" src="https://github.com/wandb/openui/assets/149228038/c124ff25-6d70-4d83-b8ad-2bb930be4b55">

@vanpelt

**Comment by alfi4000** [comment]
Its only in the settings tab everything else works!

**Comment by alfi4000** [comment]
If that works the users could run it faster just by:
git clone repo
cd openui
cd backend
docker-compose up -d

**Comment by alfi4000** [comment]
Because of my lack of knowledge I asked chatgpt but it don't know wich file executes the function so it not know how it need to be edited it gave me answers like this:   

It looks like you have an error in your web application. The error states that a <Select.Item /> element must have a value-prop that is not empty. This is because the value of Select can be set to an empty string to delete the selection and display the placeholder.

This error usually occurs when you try to render a <Select.Item /> element with an empty or undefined value prop. You should ensure that all <Select.Item /> elements in your application have a value-prop that is not empty.

Here is a simple example of how you can correct it:

<Select>

<Select.Item value="option1">Option 1</Select.Item>

<Select.Item value="option2">Option 2</Select.Item>

<Select.Item value="option3">Option 3</Select.Item>

</Select>

In this example, each <Select.Item /> element has a value-prop that is not empty. If you still have problems, let me know and I will do my best to help you.

**Comment by vanpelt** [comment]
This is now fixed in the main branch.  It was an issue with the Ollama settings bar, I [fixed it here]( https://github.com/wandb/openui/commit/897ce883786535694e4f4464f8d88e7fff62ce19#diff-63bf6295842ec46d2e4fd3de5253775b2802fd3950f422ad53b0a9b2340c093c).  I'll keep this issue open for now as it would be nice to add a docker-compose example.

**Comment by alfi4000** [comment]
Ok I'll recreate the container and hold here up to date about the result!

**Comment by alfi4000** [comment]
Yeah the Issue Is Resolved The Only thing you need to add to the project is the docker compose file and everything is good to go!

**Comment by alfi4000** [comment]
I have made a show case video it's up to you if you want to use it on the GitHub page: https://youtu.be/tQYwZL5Ke-Y

**Comment by alfi4000** [comment]
Can you by any chance tell me where the link for Ollama is set to change the url because I take the Ollama source from a different instance!?

**Comment by vanpelt** [comment]
@alfi4000 I got it all working in main within Docker Compose!  See [this section](https://github.com/wandb/openui?tab=readme-ov-file#docker-compose) of the README.

**Comment by alfi4000** [comment]
> @alfi4000 I got it all working in main within Docker Compose! See [this section](https://github.com/wandb/openui?tab=readme-ov-file#docker-compose) of the README.

Yup Really Nice!👍
