### ISSUE TITLE
can you use gemini api key instead  ?

### ISSUE THREAD

**Issue by player4sir** [wandb/openui#37]

**Comment by alfi4000** [comment]
Yeah that would be a good idea but Gemini API cost from second may on too money!

**Comment by vanpelt** [comment]
It's super simple to add models that serve with the same API as OpenAI.  The Gemini series uses a google specific api protocol so we'd have to pull in that client and add it as an option similar to the Ollama integration.  I'll keep this open and let people upvote if they feel strongly about it.

**Comment by alfi4000** [comment]
From May 10 maybe the most people won't longer want it because from then on Google charges for the api that is now still free but from March on not anymore!
