### ISSUE TITLE
Ollama Url Change Docker

### ISSUE THREAD

**Issue by sonnimon** [wandb/openui#41]
Where to edit the Ollama url because I have already on a server Ollama installed but don't run openui where I have to make the change of the Ollama url?

**Comment by MMoneer** [comment]
Hi, If the Ollama server running in the default URL (http://127.0.0.1:11434) it will work, just check the default URL to confirm it's running and select the Ollama and model from the openui setting

**Comment by MMoneer** [comment]
> Where to edit the Ollama url because I have already on a server Ollama installed but don't run openui where I have to make the change of the Ollama URL?

Hi, If the Ollama server running in the default URL (http://127.0.0.1:11434/) it will work, just check the default URL to confirm it's running and select the Ollama and model from the openui setting

**Comment by vanpelt** [comment]
Thanks @MMoneer that's correct.  @sonnimon, if for instance you're running OpenUI in a docker container you can specify the `OLLAMA_HOST` for the container to point to the right location.  See the [`docker-compose.yaml`](https://github.com/wandb/openui/blob/main/docker-compose.yaml#L18) file in this repo for an example of how I did that.

**Comment by MMoneer** [comment]
> Thanks @MMoneer that's correct. @sonnimon, if for instance you're running OpenUI in a docker container you can specify the `OLLAMA_HOST` for the container to point to the right location. See the [`docker-compose.yaml`](https://github.com/wandb/openui/blob/main/docker-compose.yaml#L18) file in this repo for an example of how I did that.

@vanpelt I'd like to suggest adding support for other OpenAI API-compatible applications, such as Lm Studio and OobaBooga.

**Comment by sonnimon** [comment]
Sorry for late response I run it on different port and ip so I just would need to change in the docker compose file the url?

**Comment by sonnimon** [comment]
Sorry I might haven't explained clear I don't run Ollama in the docker container on the same host as the openui container and  for example 192168.50.50:11435 but the openui container would be on a different host then the openui container so I would need to change the url from where the openui access the Ollama or is the openui and the docker container connected to each other the one that comes with openui!?

@MMoneer @vanpelt

**Comment by MMoneer** [comment]
@sonnimon  did you try as @vanpelt told you, check the docker-compose.yaml file and  change the ollama_host to the actual Ollama server URL, 
```
environment:
      - OLLAMA_HOST=http://ollama:11434                    
      # Just remove `=xxx` to have the env variable passed forward
      - OPENAI_API_KEY=xxx
```

**Comment by alfi4000** [comment]
> @sonnimon did you try as @vanpelt told you, check the docker-compose.yaml file and change the ollama_host to the actual Ollama server URL,
> 
> ```
> environment:
>       - OLLAMA_HOST=http://ollama:11434                    
>       # Just remove `=xxx` to have the env variable passed forward
>       - OPENAI_API_KEY=xxx
> ```

Oh now I got what you guys mention thanks !

**Comment by sonnimon** [comment]
Oh nOw I got what he mentioned I miss understood it! :/ Thanks have a great day! :)
