### ISSUE TITLE
FR - custom endpint for ollama

### ISSUE THREAD

**Issue by rony432** [wandb/openui#43]
is it possible to add custom ollama endpoint for openui in the web ui
form must have endpoint textbox and model name

thanks

**Comment by vanpelt** [comment]
Hey @rony432 the python backend proxies to ollama, by default it will try to hit http://localhost:11434.  You can set the `OLLAMA_HOST` environment variable wherever you're running the backend to have it hit a different endpoint.

**Comment by rony432** [comment]
oh, ok. thanks. 
some how i forgot it was a thing. :)
