### ISSUE TITLE
pyenv: version `openui' is not installed 

### ISSUE THREAD

**Issue by Verfinix** [wandb/openui#44]
Anyone can advise ? 

After 
git clone https://github.com/wandb/openui
cd openui/backend
# I run this in conda with python=3.12
pip install .

pyenv: version `openui' is not installed (set by /projects/openui/openui/backend/.python-version)

**Comment by vanpelt** [comment]
@Verfinix you can either create a pyenv virtual env named "openui" or cd into that directory and run `"pyenv local SOME_ENV"`.  If that's not making sense to you just remove `.python-version` from the backend directory.
