### ISSUE TITLE
Fix: the returned data cannot be rendered

### ISSUE THREAD

**Issue by YangZhiBoGreenHand** [wandb/openui#46]
If you start with docker and port 7878 is mapped to 17878, rendering will fail

**Comment by YangZhiBoGreenHand** [comment]
<img width="491" alt="image" src="https://github.com/wandb/openui/assets/105403828/634dab0f-630c-4a1f-a3e3-5b29170b33ef">
The image is self-installing your dockerfile package

**Comment by YangZhiBoGreenHand** [comment]
<img width="1640" alt="image" src="https://github.com/wandb/openui/assets/105403828/eb1f27d2-1e66-4afb-8754-0d5ada8f36ed">
If this place caused it？

**Comment by YangZhiBoGreenHand** [comment]
<img width="1006" alt="image" src="https://github.com/wandb/openui/assets/105403828/2b370e19-67af-4a62-8612-042dc12ad716">
There is html data but not render

**Comment by vanpelt** [comment]
@YangZhiBoGreenHand if you're not running the backend on the default port you'll need to rebuild the container in "hosted" mode.  From the frontend directory run:

```
npm install
npm run build -- --mode hosted
```

Then rebuild the backend container (`docker-compose build`), that should fix the issue you're seeing.  Let me know if it doesn't.
