### ISSUE TITLE
error code 404

### ISSUE THREAD

**Issue by HoangBK22** [wandb/openui#49]
I'm using gpt 3.5 turbo 
![Screenshot 2024-04-08 095744](https://github.com/wandb/openui/assets/161436100/7126f9a0-b1fd-4c83-bf7f-3fb0c61d5548)

but when i use it this appear
![Screenshot 2024-04-08 095419](https://github.com/wandb/openui/assets/161436100/6998d549-5caf-4b81-83f9-edec342a1cb1)

**Comment by vanpelt** [comment]
You need to apply for gpt4-vision-preview access to use images.  Googling should get you answers on how.

**Comment by HoangBK22** [comment]
oh okay i got it, thanks
