### ISSUE TITLE
Please help with an explanation

### ISSUE THREAD

**Issue by RFARREY** [wandb/openui#50]
I am using Ollama. I successfully installed it but now I am getting this error when I attempt a generation. Any idea where the issue stems from?

![Screenshot 2024-04-08 084507](https://github.com/wandb/openui/assets/45320379/6f06f1de-5749-4e01-9e17-2a224561272b)
![Screenshot 2024-04-08 094806](https://github.com/wandb/openui/assets/45320379/9d0d98b5-f272-44ef-8e05-193cdb307a10)

**Comment by vanpelt** [comment]
The chat history will show what the model output.  Because of the way codellama was trained you might need to alter the system prompt.  The error means it isn't returning any HTML in the output that we could parse.

I've had decent success with llava or mixtral/ mistral
