### ISSUE TITLE
Need Some UI improvements !!

### ISSUE THREAD

**Issue by Saurabh77-99** [wandb/openui#52]
Its working good, but the UI isn't that good , you can do some improvements , if you need reference for UI we can connect ! Thank you

**Comment by vanpelt** [comment]
Sure!  Send me some mockups or figma designs and I would be happy to implement.

**Comment by vanpelt** [comment]
My email is vanpelt@wandb.com if that's easier to coordinate over.

**Comment by Saurabh77-99** [comment]
> My email is [vanpelt@wandb.com](mailto:vanpelt@wandb.com) if that's easier to coordinate over.

Yup sure ! Will send you some samples asap by this weekend ! Thank you.

**Comment by Saurabh77-99** [comment]
Hey @vanpelt I have sent you a Figma design, reminder to please check your mail. Thank you!

**Comment by Saurabh77-99** [comment]
> 
Hey @vanpelt I have sent you a updated Figma design of rendering page, reminder to please check your mail. Thank you!
