### ISSUE TITLE
About the LLM

### ISSUE THREAD

**Issue by tianmagongyue** [wandb/openui#55]
> It's also a tool we're using at W&B to test and prototype our next generation tooling for building powerful applications on top of LLM's.

Is the openui a test project to train the LLM to build a more powerful applications? And I'm curious about that what kind of product is the next one going to be?

**Comment by vanpelt** [comment]
There are a number of approaches we can use to make the responses from the LLM better.  I may try fine-tuning small opensource models, or further iterating on the prompt engineering.  We're [using weave](https://wandb.github.io/weave/) to keep track of all of these experiments.

**Comment by tianmagongyue** [comment]
Thank you, I've got it.

> There are a number of approaches we can use to make the responses from the LLM better. I may try fine-tuning small opensource models, or further iterating on the prompt engineering. We're [using weave](https://wandb.github.io/weave/) to keep track of all of these experiments.
