### ISSUE TITLE
codellma怎么拉取？我没有拉取运行第四步报错

### ISSUE THREAD

**Issue by dragan2023** [wandb/openui#57]
(venv) PS F:\python project\openUI\openui\backend> export OPENAI_API_KEY=xxx
export : 无法将“export”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ export OPENAI_API_KEY=xxx（我填写了自己的API，并确保它是正确的）
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (export:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by vanpelt** [comment]
In windows I think you need to call `set` instead of `export`.  Also the original message had your key in it so I would be sure to rotate / delete that key in OpenAI and use a different one.
