### ISSUE TITLE
Fix Github Deployments

### ISSUE THREAD

**Issue by Saurabh77-99** [wandb/openui#58]
![Screenshot 2024-04-19 124210](https://github.com/wandb/openui/assets/128208555/90139f2e-de5e-4d70-8935-4fe40d1c4f44)

When i visited the Github Deployments links , it shows just ${body} with a white background.

**Comment by vanpelt** [comment]
This is actually intended.  This is the renderer that gets loaded into the preview iframe in the app itself.  It's only meant to be loaded within the main site which is hosted at openui.fly.dev.  Using github pages to deploy it is basically a hack that ensures it's running on a different domain which is required to enable securely executing arbitrary user javascript.

**Comment by Saurabh77-99** [comment]
> This is actually intended. This is the renderer that gets loaded into the preview iframe in the app itself. It's only meant to be loaded within the main site which is hosted at openui.fly.dev. Using github pages to deploy it is basically a hack that ensures it's running on a different domain which is required to enable securely executing arbitrary user javascript.

Oh alright , this hack is amazing. Got to know this for the first time and Thank you for letting me know.
