### ISSUE TITLE
ImportError: cannot import name 'reconstruct_completion' from 'weave.monitoring.openai.util'

### ISSUE THREAD

**Issue by kousw** [wandb/openui#6]
There doesn't seem to be a corresponding method in the weave package.
If you have a version that specifies it, please let me know.

at backend/openui/ollama.py
```
from weave.monitoring.openai.util import (
    reconstruct_completion,
)
```

**Comment by rossman22590** [comment]
same issue :(

**Comment by ramusbucket** [comment]
It seems `reconstruct_completion` has been removed in the latest release (https://github.com/wandb/weave/commit/7157c82c59536981918f668a2be03009114a3f74#diff-30840bac4fcdf610b7bfff00b61ada36f17f92620172f41c31bf4a12bf33d5e4).

Uninstall `weave` package and install 0.44.0 version.
