### ISSUE TITLE
不展示web页面

### ISSUE THREAD

**Issue by qn2060** [wandb/openui#61]
你好，请问为什么我这一直出不来生成的web页面呢？
![微信截图_20240424094925](https://github.com/wandb/openui/assets/15309040/ebba96bd-7d62-46ed-957b-8fee6694145b)

我的启动命令是
docker run --rm --network host -e OPENAI_API_KEY=xxx -e OLLAMA_HOST=http://IP:11434 openui

用的版本是昨天pull的版本  打包的本地docker镜像  就是一直出不来上边的动态展示界面

用的模型是llava:latest

日志：
wandb: Unpatching OpenAI completions
INFO (openui):  Starting OpenUI AI Server created by W&B...
INFO (openui):  Running API Server
INFO (uvicorn.error):  Started server process [1]
INFO (uvicorn.error):  Waiting for application startup.
DEBUG (openui):  Starting up server in 1...
INFO (uvicorn.error):  Application startup complete.
INFO (uvicorn.error):  Uvicorn running on http://0.0.0.0:7878 (Press CTRL+C to quit)
INFO (uvicorn.access):  10.1.242.14:60572 - "GET / HTTP/1.1" 200
INFO (uvicorn.access):  10.1.242.14:60572 - "GET /assets/index-BHikIWif.js HTTP/1.1" 304
INFO (uvicorn.access):  10.1.242.14:60572 - "GET /assets/index-Bgl3Xq1c.js HTTP/1.1" 304
INFO (uvicorn.access):  10.1.242.14:60571 - "GET /assets/textarea-DJqcuMOF.js HTTP/1.1" 304
INFO (uvicorn.access):  10.1.242.14:60571 - "GET /v1/session HTTP/1.1" 200
INFO (uvicorn.access):  10.1.242.14:60571 - "GET /assets/Builder-C6_EycKe.js HTTP/1.1" 304
INFO (uvicorn.access):  10.1.242.14:60572 - "GET /v1/ollama/tags HTTP/1.1" 200
DEBUG (openui):  Encoding llama data
DEBUG (openui):  Booting up ollama...
INFO (uvicorn.access):  10.1.242.14:60599 - "POST /v1/chat/completions HTTP/1.1" 200
INFO (uvicorn.access):  10.1.242.14:60613 - "GET /assets/CodeEditor-sJNrBefa.js HTTP/1.1" 304
INFO (uvicorn.access):  10.1.242.14:60613 - "GET /assets/SyntaxHighlighter-Cghb3F9F.js HTTP/1.1" 304
DEBUG (openui):  Encoding llama data
DEBUG (openui):  Booting up ollama...
INFO (uvicorn.access):  10.1.242.14:60660 - "POST /v1/chat/completions HTTP/1.1" 200

**Comment by vanpelt** [comment]
This should be fixed in master now!  Let me know if that's not the case.

**Comment by qn2060** [comment]
@vanpelt  我重新拉取最新的代码，重新build docker 镜像，还是看不到web展示
![image](https://github.com/wandb/openui/assets/15309040/99873b7a-088d-4e21-a6ac-95bc5e9b821e)

![image](https://github.com/wandb/openui/assets/15309040/4125f822-21a8-44c4-86ab-fdf2b298b112)

日志开起来一切正常
docker log：

wandb: Unpatching OpenAI completions
INFO (openui):  Starting OpenUI AI Server created by W&B...
INFO (openui):  Running API Server
INFO (uvicorn.error):  Started server process [1]
INFO (uvicorn.error):  Waiting for application startup.
DEBUG (openui):  Starting up server in 1...
INFO (uvicorn.error):  Application startup complete.
INFO (uvicorn.error):  Uvicorn running on http://0.0.0.0:7878 (Press CTRL+C to quit)
INFO (uvicorn.access):  10.1.242.14:53227 - "GET /ai/2tnabPg69hjGJstieg0dN HTTP/1.1" 200
INFO (uvicorn.access):  10.1.242.14:53227 - "GET /assets/index-BHikIWif.js HTTP/1.1" 304
INFO (uvicorn.access):  10.1.242.14:53228 - "GET /assets/index-1-JB3fie.css HTTP/1.1" 304
INFO (uvicorn.access):  10.1.242.14:53229 - "GET /assets/vendor-BGjp6CLF.js HTTP/1.1" 304
INFO (uvicorn.access):  10.1.242.14:53227 - "GET /favicon.png HTTP/1.1" 200
INFO (uvicorn.access):  10.1.242.14:53229 - "GET /assets/index-Bgl3Xq1c.js HTTP/1.1" 304
INFO (uvicorn.access):  10.1.242.14:53228 - "GET /assets/textarea-DJqcuMOF.js HTTP/1.1" 304
INFO (uvicorn.access):  10.1.242.14:53229 - "GET /assets/Builder-C6_EycKe.js HTTP/1.1" 304
INFO (uvicorn.access):  10.1.242.14:53229 - "GET /assets/CodeEditor-sJNrBefa.js HTTP/1.1" 304
INFO (uvicorn.access):  10.1.242.14:53229 - "GET /assets/SyntaxHighlighter-Cghb3F9F.js HTTP/1.1" 304
INFO (uvicorn.access):  10.1.242.14:53229 - "GET /v1/session HTTP/1.1" 200
INFO (uvicorn.access):  10.1.242.14:53227 - "GET /assets/standalone-TZraShkH.js HTTP/1.1" 304
INFO (uvicorn.access):  10.1.242.14:53228 - "GET /v1/ollama/tags HTTP/1.1" 200
INFO (uvicorn.access):  10.1.242.14:53228 - "GET /assets/html-D7SVdXI-.js HTTP/1.1" 304
DEBUG (openui):  Encoding llama data
DEBUG (openui):  Booting up ollama...
INFO (uvicorn.access):  10.1.242.14:53261 - "POST /v1/chat/completions HTTP/1.1" 200

**Comment by vanpelt** [comment]
So sorry, I forgot to build the frontend assets with the new logic.  If you pull main and rebuild the container it should work now 🤞
