### ISSUE TITLE
downloaded html looks different from the preview

### ISSUE THREAD

**Issue by jiojiojackson** [wandb/openui#63]
the downloaded html looks different from the preview, as showed below. How can I solve this?
![download](https://github.com/wandb/openui/assets/128605081/751ba87a-a696-46e9-8e6c-10bb4c96d84a)
![preview](https://github.com/wandb/openui/assets/128605081/c2c72464-b9a0-4244-9c71-c0f67166013f)

**Comment by vanpelt** [comment]
The generated HTML requires tailwindcss.  See [this issue](https://github.com/wandb/openui/issues/19#issuecomment-2033119664) with a description of how to wrap the HTML.

**Comment by vanpelt** [comment]
I'm actually going to keep this open and figure out a way to make this clearer as you're not the only one having this issue.

**Comment by ornell** [comment]
Good that you are keeping this open :) Something should be added in the readme for this until there is a fix in place. This isn't only an issue if you copy paste the generated code, but also if you use the download button. If this was only a copy paste problem it wouldn't be a biggie, but this will hinder most users from using the software.

**Comment by vanpelt** [comment]
This is now fixed in master!
