### ISSUE TITLE
Support Angular generation 

### ISSUE THREAD

**Issue by bonelli** [wandb/openui#67]
I would like to generate Angular components with this awesome project, is there any theoretical issue in implementing this or do you think it is possible?

**Comment by vanpelt** [comment]
Should be possible, I'll look into adding that option.

**Comment by bibintjohn1** [comment]
@vanpelt , did you get chance to check feasibility of generating "Angular" components?

**Comment by vanpelt** [comment]
Just added it to the main branch, haven't tested it but it's now an option in the menu.  Curious to hear how you think it does as it's just asking the LLM to make the HTML "Angular"
