### ISSUE TITLE
Getting `ImportError: cannot import name 'AsyncStream'

### ISSUE THREAD

**Issue by irom77** [wandb/openui#85]
Getting 

`ImportError: cannot import name 'AsyncStream' from partially initialized module 'openai' (most likely due to a circular import) (E:\JupyterNotebooks\openui\backend\openui\openai.py)`

Tried _**python -m pip install openai**_ --upgrade but it didn't help. Using Python 3.11.8

**Comment by vanpelt** [comment]
Ahh, be sure to run the code from the `backend` directory.  You'll get this error if you run in a directory that has a one office or die named openai
