### ISSUE TITLE
You MIGGGGGGGGht want to censor it a little

### ISSUE THREAD

**Issue by stpv221** [wandb/openui#88]
so I uploaded this image:
![image](https://github.com/wandb/openui/assets/167645243/d20cf51e-0956-46c8-857c-3adaf83d53ae)
and got some rather interesting code:
<div class="max-w-screen-xl mx-auto px-4">
  <header class="py-4">
    <h1 class="text-3xl font-bold text-center">Corn Hub</h1>
  </header>
  <section class="mt-8">
    <h2 class="text-2xl font-semibold mb-4">Hot Corn Videos</h2>
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
      <div class="bg-white shadow rounded overflow-hidden">
        <img src="https://placehold.co/300x200" alt="Video thumbnail" />
        <div class="p-4">
          <h3 class="font-semibold">Sizzle on the cob</h3>
          <p class="text-sm text-zinc-600">450 views • 2h ago</p>
        </div>
      </div>
    </div>
  </section>

  <section class="mt-8">
    <h2 class="text-2xl font-semibold mb-4">Most Viewed Corn Videos</h2>
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4"></div>
  </section>

  <section class="mt-8">
    <h2 class="text-2xl font-semibold mb-4">Recommended for You</h2>
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4"></div>
  </section>

  <footer class="py-4 mt-8 text-center">
    <p>Cornhub not your thing? Go to Pornhub</p>
  </footer>
</div>

**Comment by racinette** [comment]
why would you censor a locally running neural network, duh

**Comment by vanpelt** [comment]
LOL
