### ISSUE TITLE
Webpage Title Adjustment: Elemint > Element

### ISSUE THREAD

**Issue by Candice-Louw** [wandb/openui#89]
It may have been done on purpose (in that case, please feel free to close this issue 😄 ), but the title on the hosted/demo instance webpage reads "Create a new Elemint".
![image](https://github.com/wandb/openui/assets/65529128/bd7f0b0e-af14-46ec-9103-981bca39ba20)

The correct spelling would be "Create a new Element" - see https://www.dictionary.com/browse/element.

<hr/>

Unrelated: Thanks for the cool tool and sharing it with the open-source community! 👏

**Comment by vanpelt** [comment]
It's fixed in master.  I'll cut a new release.  Originally I called the project "Elemint" like a thing that "mint's" elements.  Alas, that name was lame 😝
