### ISSUE TITLE
wierd issue

### ISSUE THREAD

**Issue by rossman22590** [wandb/openui#9]
$ python -m openui
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "J:\Github\openui\backend\openui\__main__.py", line 3, in <module>      
    from . import server
  File "J:\Github\openui\backend\openui\server.py", line 16, in <module>       
    from fastapi_sso.sso.github import GithubSSO
ModuleNotFoundError: No module named 'fastapi_sso'

**Comment by vanpelt** [comment]
This is strange.  Maybe a virtual env issue?  Can you try running `pip install -U fastapi-sso` and sharing the output?

**Comment by JCMathonet** [comment]
I Have a similar issue:
python3 -m openui
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/jcm/openui/backend/openui/__main__.py", line 3, in <module>
    from . import server
  File "/Users/jcm/openui/backend/openui/server.py", line 3, in <module>
    from fastapi.responses import (
ModuleNotFoundError: No module named 'fastapi'
and I did install FastAPI-sso as follows:
pip install -U fastapi-sso
Any suggestion?

**Comment by Daeliel** [comment]
Same issue here: 

(env) (base) F:\pinokio\api\openui.git\app\backend>pip install -U fastapi_sso
Requirement already satisfied: fastapi_sso in f:\pinokio\api\openui.git\app\backend\env\lib\site-packages (0.15.0)
Requirement already satisfied: httpx>=0.23.0 in f:\pinokio\api\openui.git\app\backend\env\lib\site-packages (from fastapi_sso) (0.27.0)
Requirement already satisfied: pydantic[email]>=1.8.0 in f:\pinokio\api\openui.git\app\backend\env\lib\site-packages (from fastapi_sso) (2.8.2)
Requirement already satisfied: fastapi>=0.80 in f:\pinokio\api\openui.git\app\backend\env\lib\site-packages (from fastapi_sso) (0.111.0)
Requirement already satisfied: oauthlib>=3.1.0 in f:\pinokio\api\openui.git\app\backend\env\lib\site-packages (from fastapi_sso) (3.2.2)
Requirement already satisfied: ujson!=4.0.2,!=4.1.0,!=4.2.0,!=4.3.0,!=5.0.0,!=5.1.0,>=4.0.1 in f:\pinokio\api\openui.git\app\backend\env\lib\site-packages (from fastapi>=0.80->fastapi_sso) (5.10.0)
Requirement already satisfied: python-multipart>=0.0.7 in f:\pinokio\api\openui.git\app\backend\env\lib\site-packages (from fastapi>=0.80->fastapi_sso) (0.0.9)
Requirement already satisfied: orjson>=3.2.1 in f:\pinokio\api\openui.git\app\backend\env\lib\site-packages (from fastapi>=0.80->fastapi_sso) (3.10.6)
Requirement already satisfied: starlette<0.38.0,>=0.37.2 in f:\pinokio\api\openui.git\app\backend\env\lib\site-packages (from fastapi>=0.80->fastapi_sso) (0.37.2)
Requirement already satisfied: email_validator>=2.0.0 in f:\pinokio\api\openui.git\app\backend\env\lib\site-packages (from fastapi>=0.80->fastapi_sso) (2.2.0)
Requirement already satisfied: jinja2>=2.11.2 in f:\pinokio\api\openui.git\app\backend\env\lib\site-packages (from fastapi>=0.80->fastapi_sso) (3.1.4)
Requirement already satisfied: typing-extensions>=4.8.0 in f:\pinokio\api\openui.git\app\backend\env\lib\site-packages (from fastapi>=0.80->fastapi_sso) (4.12.2)
Requirement already satisfied: fastapi-cli>=0.0.2 in f:\pinokio\api\openui.git\app\backend\env\lib\site-packages (from fastapi>=0.80->fastapi_sso) (0.0.4)
Requirement already satisfied: uvicorn[standard]>=0.12.0 in f:\pinokio\api\openui.git\app\backend\env\lib\site-packages (from fastapi>=0.80->fastapi_sso) (0.30.1)
Requirement already satisfied: certifi in f:\pinokio\api\openui.git\app\backend\env\lib\site-packages (from httpx>=0.23.0->fastapi_sso) (2024.7.4)
Requirement already satisfied: anyio in f:\pinokio\api\openui.git\app\backend\env\lib\site-packages (from httpx>=0.23.0->fastapi_sso) (4.4.0)
Requirement already satisfied: httpcore==1.* in f:\pinokio\api\openui.git\app\backend\env\lib\site-packages (from httpx>=0.23.0->fastapi_sso) (1.0.5)
Requirement already satisfied: sniffio in f:\pinokio\api\openui.git\app\backend\env\lib\site-packages (from httpx>=0.23.0->fastapi_sso) (1.3.1)
Requirement already satisfied: idna in f:\pinokio\api\openui.git\app\backend\env\lib\site-packages (from httpx>=0.23.0->fastapi_sso) (3.7)
Requirement already satisfied: h11<0.15,>=0.13 in f:\pinokio\api\openui.git\app\backend\env\lib\site-packages (from httpcore==1.*->httpx>=0.23.0->fastapi_sso) (0.14.0)
Requirement already satisfied: pydantic-core==2.20.1 in f:\pinokio\api\openui.git\app\backend\env\lib\site-packages (from pydantic[email]>=1.8.0->fastapi_sso) (2.20.1)
Requirement already satisfied: annotated-types>=0.4.0 in f:\pinokio\api\openui.git\app\backend\env\lib\site-packages (from pydantic[email]>=1.8.0->fastapi_sso) (0.7.0)
Requirement already satisfied: dnspython>=2.0.0 in f:\pinokio\api\openui.git\app\backend\env\lib\site-packages (from email_validator>=2.0.0->fastapi>=0.80->fastapi_sso) (2.6.1)
Requirement already satisfied: typer>=0.12.3 in f:\pinokio\api\openui.git\app\backend\env\lib\site-packages (from fastapi-cli>=0.0.2->fastapi>=0.80->fastapi_sso) (0.12.3)
Requirement already satisfied: MarkupSafe>=2.0 in f:\pinokio\api\openui.git\app\backend\env\lib\site-packages (from jinja2>=2.11.2->fastapi>=0.80->fastapi_sso) (2.1.5)
Requirement already satisfied: exceptiongroup>=1.0.2 in f:\pinokio\api\openui.git\app\backend\env\lib\site-packages (from anyio->httpx>=0.23.0->fastapi_sso) (1.2.1)
Requirement already satisfied: click>=7.0 in f:\pinokio\api\openui.git\app\backend\env\lib\site-packages (from uvicorn[standard]>=0.12.0->fastapi>=0.80->fastapi_sso) (8.1.7)
Requirement already satisfied: pyyaml>=5.1 in f:\pinokio\api\openui.git\app\backend\env\lib\site-packages (from uvicorn[standard]>=0.12.0->fastapi>=0.80->fastapi_sso) (6.0.1)
Requirement already satisfied: websockets>=10.4 in f:\pinokio\api\openui.git\app\backend\env\lib\site-packages (from uvicorn[standard]>=0.12.0->fastapi>=0.80->fastapi_sso) (12.0)
Requirement already satisfied: httptools>=0.5.0 in f:\pinokio\api\openui.git\app\backend\env\lib\site-packages (from uvicorn[standard]>=0.12.0->fastapi>=0.80->fastapi_sso) (0.6.1)
Requirement already satisfied: colorama>=0.4 in f:\pinokio\api\openui.git\app\backend\env\lib\site-packages (from uvicorn[standard]>=0.12.0->fastapi>=0.80->fastapi_sso) (0.4.6)
Requirement already satisfied: watchfiles>=0.13 in f:\pinokio\api\openui.git\app\backend\env\lib\site-packages (from uvicorn[standard]>=0.12.0->fastapi>=0.80->fastapi_sso) (0.22.0)
Requirement already satisfied: python-dotenv>=0.13 in f:\pinokio\api\openui.git\app\backend\env\lib\site-packages (from uvicorn[standard]>=0.12.0->fastapi>=0.80->fastapi_sso) (1.0.1)
Requirement already satisfied: rich>=10.11.0 in f:\pinokio\api\openui.git\app\backend\env\lib\site-packages (from typer>=0.12.3->fastapi-cli>=0.0.2->fastapi>=0.80->fastapi_sso) (13.7.1)
Requirement already satisfied: shellingham>=1.3.0 in f:\pinokio\api\openui.git\app\backend\env\lib\site-packages (from typer>=0.12.3->fastapi-cli>=0.0.2->fastapi>=0.80->fastapi_sso) (1.5.4)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in f:\pinokio\api\openui.git\app\backend\env\lib\site-packages (from rich>=10.11.0->typer>=0.12.3->fastapi-cli>=0.0.2->fastapi>=0.80->fastapi_sso) (2.18.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in f:\pinokio\api\openui.git\app\backend\env\lib\site-packages (from rich>=10.11.0->typer>=0.12.3->fastapi-cli>=0.0.2->fastapi>=0.80->fastapi_sso) (3.0.0)
Requirement already satisfied: mdurl~=0.1 in f:\pinokio\api\openui.git\app\backend\env\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer>=0.12.3->fastapi-cli>=0.0.2->fastapi>=0.80->fastapi_sso) (0.1.2)

[notice] A new release of pip is available: 23.0.1 -> 24.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

(env) (base) F:\pinokio\api\openui.git\app\backend>python -m openui
Traceback (most recent call last):
  File "F:\pinokio\bin\miniconda\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "F:\pinokio\bin\miniconda\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\pinokio\api\openui.git\app\backend\openui\__main__.py", line 3, in <module>
    from . import server
  File "F:\pinokio\api\openui.git\app\backend\openui\server.py", line 3, in <module>
    from fastapi_sso.github import GithubSSO
ModuleNotFoundError: No module named 'fastapi_sso.github'
