### ISSUE TITLE
THe text editor does not update the code so if i change a color it does not reflect making the experience bad, I cant even add my own code or collaborate with it technically

### ISSUE THREAD

**Issue by PhillipGimmi** [wandb/openui#94]

**Comment by vanpelt** [comment]
I had this working at one point.  Will try to bring it back soon

**Comment by UNES97** [comment]
I have the same issue, after relaoding a couple of times it works.

**Comment by vanpelt** [comment]
Yeah, I saw this in Michael's video.  I'll try to reproduce and figure out what's up...

**Comment by vanpelt** [comment]
This should be fixed now...
