### ISSUE TITLE
cannot use non loopback addresses

### ISSUE THREAD

**Issue by VincentJGeisler** [wandb/openui#98]
Im trying to install this on an AI server. 

our ollama instance is running on a different machine, so problem 1. but i also cannot connect to this docker because the server is headless, i can't connect remotely to the loopback. 

how do i make this listen on another address? 

 ports:
      - "10.10.1.121:7878:7878"
 in the docker yaml Seems to have no effect

**Comment by vanpelt** [comment]
Set the OLLAMA_HOST env variable
